# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Configuration for sanity checking.

!obj:experiments.FitPredictErrorExperiment {
  backend: &be !obj:backends.CPU {
    rng_seed: 0,
  },

  dataset: &ds !obj:datasets.ToyImages {
    backend: *be,
    repo_path: '/usr/local/data',
    sample_pct: 100,
  },

  model: !obj:models.ConvnetDist {
    backend: *be,
    num_epochs: 2,
    batch_size: &bs 32,
    learning_rate: &lr 0.01,
    dataset: *ds,
    layers: [
      !obj:layers.deprecated.layer.ConvLayerDist {
        name: layer0,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rule: !obj:optimizers.GradientDescentMomentum {
          name: layer0lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: &mm {
              type: linear_monotone,
              initial_coef: 0.99,
              start_epoch: 5,
              saturate_epoch: 5,
              saturated_coef: 0.90,
            },
          },
        },
        nifm: 3,
        nofm: 16,
        ifmshape: [32, 32],
        fshape: [3, 3],
        stride: 1,
        weight_init: !obj:params.UniformValGen {
          backend: *be,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:layers.deprecated.layer.MaxPoolingLayerDist {
        name: layer1,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        nifm: 16,
        ifmshape: [30, 30],
        fshape: [2, 2],
        stride: 2,
      },
      !obj:layers.deprecated.layer.LayerDist {
        name: layer6,
        backend: *be,
        batch_size: *bs,
        pos: 2,
        learning_rule: !obj:optimizers.GradientDescentMomentum {
          name: layer6lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 3600,
        nout: 100,
        activation: !obj:transforms.RectLin {},
        weight_init: !obj:params.UniformValGen {
          backend: *be,
          low: -0.1,
          high: 0.1,
        },
      },
      &lastlayer !obj:layers.deprecated.layer.LayerDist {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 3,
        learning_rule: !obj:optimizers.GradientDescentMomentum {
          name: outputlr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 100,
        nout: 2,
        activation: !obj:transforms.Logistic {},
        weight_init: !obj:params.UniformValGen {
          backend: *be,
          low: -0.1,
          high: 0.1,
        },
      },
    ],
    cost: !obj:transforms.CrossEntropy {
      olayer: *lastlayer,
      shortcut_deriv: False,
    },
  },

  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
