# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a 1 hidden layer Neural Net on full
# MNIST.  Parameters are optimized for performance.

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:neon.backends.fixedpoint.FixedPoint {
    rng_seed: 0,
    seterr_handling: {
      all: 'raise',
    },
    default_dtype: &def_dtype !obj:neon.backends.fixedpoint.fixpt_dtype {
      sign_bit: True,
      int_bits: 0,
      frac_bits: 15,
      overflow: 0,
      rounding: 0
    },
  },

  datasets: [
    # MNIST data
    !obj:neon.datasets.mnist.MNIST {
      backend: *be,
      repo_path: '/usr/local/data',
      sample_pct: 100,
      serialized_path: '/usr/local/data/MNIST/mnist-FixedPoint.pkl',
    },
  ],

  # simple MLP model specification
  model: !obj:neon.models.mlp.MLP {
    backend: *be,
    num_epochs: 60,
    batch_size: &bs 100,
    learning_rate: &lr 0.01,
    momentum: {
      type: constant, # linear_monotone, nesterov
      coef: 0.90,
    },
    cost: !obj:neon.transforms.cross_entropy.CrossEntropy {},
    serialized_path: './mlp-fixpt_simple.pkl',
    layers: [
      !obj:neon.models.layer.Layer {
        name: h0,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rate: *lr,
        nin: 784,
        nout: 2000,
        activation: !obj:neon.transforms.rectified.RectLin {},
        weight_init: !obj:params.GaussianValGen {
          backend: *be,
          loc: 0.0,
          scale: 0.01,
          bias_init: 0.0,
        },
        weight_dtype: *def_dtype,
        velocity_dtype: *def_dtype,
        updates_dtype: *def_dtype,
        pre_act_dtype: !obj:neon.backends.fixedpoint.fixpt_dtype {
          sign_bit: False,
          int_bits: 2,
          frac_bits: 14,
          overflow: 0,
          rounding: 0
        },
        output_dtype: !obj:neon.backends.fixedpoint.fixpt_dtype {
          sign_bit: False,
          int_bits: 0,
          frac_bits: 16,
          overflow: 0,
          rounding: 0
        },
      },
      !obj:neon.models.layer.Layer {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        learning_rate: *lr,
        nin: 2000,
        nout: 10,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: !obj:params.NodeNormalizedValGen {
          backend: *be,
          scale: 4.0,
          bias_init: 0.0,
        },
        weight_dtype: *def_dtype,
        velocity_dtype: *def_dtype,
        updates_dtype: *def_dtype,
        pre_act_dtype: !obj:neon.backends.fixedpoint.fixpt_dtype {
          sign_bit: False,
          int_bits: 2,
          frac_bits: 14,
          overflow: 0,
          rounding: 0
        },
        output_dtype: !obj:neon.backends.fixedpoint.fixpt_dtype {
          sign_bit: False,
          int_bits: 0,
          frac_bits: 16,
          overflow: 0,
          rounding: 0
        },
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 10,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
