# Data parallel version of convnet
# Experiment settings to train/test a CNN on MNIST.
# Run with 3 MPI-processes (num_procs) if using this yaml file
# change batch-size accordingly if running with diff num_procs.
# model batch size should be datasets.batch_size / num_procs

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  dist_flag: &df True,
  backend: &be !obj:neon.backends.gpu.GPUDataDist {
    rng_seed: 0,
  },

  dataset: !obj:neon.datasets.mnist.MNIST {
    dist_flag: *df,
    dist_mode: &dm 'datapar', # data parallel
    backend: *be,
    repo_path: '/usr/local/data',
    # serialized_path: '/usr/local/data/MNIST-datapar_{size}/mnist-Gpu_{rank}.pkl',
    sample_pct: 10,
    # datapar specific parameters
    batch_size: 300,
    num_test_sample: 9000,
  },

  # CNN model specification
  # essentially a multi-layer perceptron with convolutional and pooling layers
  model: !obj:neon.models.mlp.MLP {
    backend: *be,
    num_epochs: 30,
    dist_mode: *dm,
    batch_size: &bs 100, # this should be datasets.batch_size / num_procs
    serialized_path: './mnist-datapar-gpu-cnn_{size}.pkl',
    layers: [
      !obj:neon.models.layer.ConvLayer {
        name: layer1,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rule: !obj:neon.models.learning_rule.GradientDescent {
          name: l1lr,
          lr_params: {
            learning_rate: &lr 0.01,
            backend: *be,
          },
        },
        nifm: 1,
        nofm: 32,
        ifmshape: [28, 28],
        fshape: [5, 5],
        stride: 1,
        weight_init: &wt_init !obj:params.UniformValGen {
          backend: *be,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:neon.models.layer.MaxPoolingLayer {
        name: layer2,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        nifm: 32,
        ifmshape: [24, 24],
        fshape: [2, 2],
        stride: 2,
      },
      !obj:neon.models.layer.ConvLayer {
        name: layer3,
        backend: *be,
        batch_size: *bs,
        pos: 2,
        learning_rule: !obj:neon.models.learning_rule.GradientDescent {
          name: l3lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
          },
        },
        nifm: 32,
        nofm: 64,
        ifmshape: [12, 12],
        fshape: [5, 5],
        stride: 1,
        weight_init: *wt_init,
      },
      !obj:neon.models.layer.MaxPoolingLayer {
        name: layer4,
        backend: *be,
        batch_size: *bs,
        pos: 3,
        nifm: 64,
        ifmshape: [8, 8],
        fshape: [2, 2],
        stride: 2,
      },
      !obj:neon.models.layer.Layer {
        name: layer5,
        backend: *be,
        batch_size: *bs,
        pos: 4,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: l4lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: &mm {
              type: linear_monotone, #constant, nesterov
              initial_coef: 0.99,
              start_epoch: 5,
              saturate_epoch: 5,
              saturated_coef: 0.90,
            },
          },
        },
        nin: 1024, # nifm * ((ih - ph) / stride + 1) * ((iw - pw) / stride + 1)
        nout: 500,
        activation: !obj:neon.transforms.rectified.RectLin {},
        weight_init: *wt_init,
      },
      &lastlayer !obj:neon.models.layer.Layer {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 5,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: l5lr,
          lr_params: {
            backend: *be,
            learning_rate: *lr,
            momentum_params: *mm,
          },
        },
        nin: 500,
        nout: 10,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: *wt_init,
      },
    ],
    cost: !obj:neon.transforms.cross_entropy.CrossEntropy {
      olayer: *lastlayer,
    },
  },
  
  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
