# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Localization experiment for Hurricane data. Loads weights from pretraining
# and applies them to larger

!obj:experiments.LocalizationExperiment {
#   # manaully specify backend like in the old times, it does not deserialize
#   backend: &be !obj:neon.backends.cpu.CPU {
#     rng_seed: 0,
#     par: !obj:neon.backend.par.NoPar { *be, },
#   },

  dataset: !obj:datasets.Hurricane {
      repo_path: '/usr/local/data/',
      hdf5_file: 'hurricanes.h5',
      # variables: [0],  # used in singlevar case
      crop: 32,  # train on 16 run on 32
      training_size: 10000,
      test_size: 10000,
  },

  weight_inits: [
    &wt_init !obj:params.UniformValGen {
      low: -0.1,
      high: 0.1,
    },
  ],

  lrules: [
      &gdm {
        type: gradient_descent_momentum,
        lr_params: {
          learning_rate: 0.01,
          momentum_params: {
            type: constant, # linear_monotone, nesterov
            coef: 0.90,
          },
        },
      },
  ],

  # Deserialize the pre-trained localization model
  model: !obj:models.MLPL {
    num_epochs: 5,
    batch_size: &bs 100,
    deserialized_path: './hurr16features.pkl',  # no learning, read filters
  },

  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}

