# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a CNN on MNIST.

!obj:experiments.FitPredictErrorExperiment {

  # MNIST data
  dataset: &ds !obj:datasets.MNIST {
    repo_path: '~/data',
    sample_pct: 10,
  },

  metrics: {
    train: [
      !obj:metrics.MisclassPercentage {},
    ],
    test: [
      !obj:metrics.MisclassPercentage {},
    ],
  },

  weight_init: &wt_init !obj:params.UniformValGen {
    low: -0.1,
    high: 0.1,
  },

  lrules: [
    &gdm {
      type: gradient_descent_momentum,
      lr_params: {
        learning_rate: 0.01,
        momentum_params: {
          type: constant, # linear_monotone, nesterov
          coef: 0.90,
        },
      },
    },
    &ada {
      type: adadelta,
      lr_params: {
        rho: &ro 0.95,
        epsilon: &eps 0.000001,
      },
    },
  ],
  # CNN model specification
  # essentially a multi-layer perceptron with convolutional and pooling layers
  model: !obj:models.MLP {
    num_epochs: 5,
    batch_size: &bs 128,
    pickle: '~/data/mnist-mlp-alex.pkl',
    # depickle: '~/data/mnist-mlp-alex.pkl',

    # serialized_path: '~/data/mnist-mlp-simple-alex.pkl',
    # deserialized_path: '~/data/mnist-mlp-simple-alex.pkl',
    layers: [
      &datalayer !obj:layers.DataLayer {
        name: d0,
        nout: 784,
      },
      !obj:layers.ConvLayer {
        name: layer1,
        nofm: 16,
        fshape: [5, 5],
        weight_init: *wt_init,
        lrule_init: *gdm,
      },
      !obj:layers.PoolingLayer {
        name: layer2,
        op: 'max',
        fshape: [2, 2],
        stride: 2,
      },
      !obj:layers.ConvLayer {
        name: layer3,
        nofm: 32,
        fshape: [5, 5],
        weight_init: *wt_init,
        lrule_init: *gdm,
      },
      !obj:layers.PoolingLayer {
        name: layer4,
        op: 'max',
        fshape: [2, 2],
        stride: 2,
      },
      !obj:layers.FCLayer {
        name: layer5,
        nout: 500,
        activation: !obj:transforms.RectLin {},
        weight_init: *wt_init,
        lrule_init: *gdm,
      },
      &lastlayer !obj:layers.FCLayer {
        name: output,
        nout: 10,
        activation: !obj:transforms.Logistic {},
        weight_init: *wt_init,
        lrule_init: *gdm,
      },
      &costlayer !obj:layers.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:transforms.CrossEntropy {},
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
