# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# MLP on CIFAR-10

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:neon.backends.cpu.CPU {
    rng_seed: 0,
  },

  datasets: [
    !obj:neon.datasets.cifar10.CIFAR10 {
      backend: *be,
      repo_path: '/usr/local/data',
      sample_pct: 10,
      # serialized_path: '/usr/local/data/CIFAR10/cifar10_10pct-Cpu.pkl',
    },
  ],

  # simple MLP model specification
  model: !obj:neon.models.mlp.MLP {
    backend: *be,
    num_epochs: 100,
    batch_size: &bs 100,
    layers: [
      !obj:neon.models.layer.Layer {
        name: h0,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: h0lr,
          lr_params: {
            learning_rate: &lr 0.01,
            backend: *be,
            momentum_params: &mm {
              type: constant, #constant, nesterov, linear_monotone
              coef: 0.90,
            },
          },
        },
        nin: 3072,
        nout: 200,
        activation: !obj:neon.transforms.rectified.RectLin {},
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:neon.models.layer.BranchLayer {
        name: blayer,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        nin: 200,
        sublayers: [
          !obj:neon.models.layer.Layer {
            name: blayer1,
            backend: *be,
            batch_size: *bs,
            pos: 1,
            learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
              name: outputlr,
              lr_params: {
                learning_rate: *lr,
                backend: *be,
                momentum_params: *mm,
              },
            },
            nin: 200,
            nout: 40,
            activation: !obj:neon.transforms.logistic.Logistic {},
            weight_init: {
              type: uniform,
              low: -0.1,
              high: 0.1,
            },
          },
          !obj:neon.models.layer.Layer {
            name: blayer2,
            backend: *be,
            batch_size: *bs,
            pos: 1,
            learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
              name: outputlr,
              lr_params: {
                learning_rate: *lr,
                backend: *be,
                momentum_params: *mm,
              },
            },
            nin: 200,
            nout: 10,
            activation: !obj:neon.transforms.rectified.RectLin {},
            weight_init: {
              type: uniform,
              low: -0.1,
              high: 0.1,
            },
          },
        ],
      },
      &lastlayer !obj:neon.models.layer.Layer {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 2,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: outputlr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 50,
        nout: 10,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
    ],
    cost: !obj:neon.transforms.cross_entropy.CrossEntropy {
      olayer: *lastlayer,
    },
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
