# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a 1 hidden layer Neural Net on full
# Iris dataset.  Simple network meant more as a sanity check.

!obj:neon.experiments.write_error_to_file.WriteErrorToFile {
  filename: neon_result_validation.txt,
  backend: &be !obj:neon.backends.cpu.CPU {
    rng_seed: 0,
    seterr_handling: {
      all: 'warn',
    },
  },

  dataset: &ds !obj:neon.datasets.iris.Iris {
    backend: *be,
    repo_path: '/usr/local/data',
    sample_pct: 100,
  },

  weight_init: &wt_init {
    type: uniform,
    low: -1,
    high: 1,
    bias_init: 0.0,
  },

  lrule: &gdm {
    type: gradient_descent_momentum,
    lr_params: {
      learning_rate: !hyperopt stepsize FLOAT 0.1 1 , # instead of a fixed 0.1, spearmint
      backend: *be,
      momentum_params: {
        type: constant,
        coef: 0,
      },
    },
  },
  # simple MLP model specification
  model: !obj:neon.models.mlp.MLPB {
    backend: *be,
    num_epochs: !hyperopt epochs INT 100 200,
    batch_size: &bs 30,
    layers: [
      &datalayer !obj:neon.models.layer2.DataLayer {
        name: d0,
        dataset: *ds,
        nout: 4,
      },
      !obj:neon.models.layer2.FCLayer {
        name: h0,
        nout: !hyperopt numberneurons INT 3 10, # instead of fixed 2
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:neon.transforms.logistic.Logistic {},
      },
      &lastlayer !obj:neon.models.layer2.FCLayer {
        name: output,
        nout: 3, # classes
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:neon.transforms.logistic.Logistic {},
      },
      &costlayer !obj:neon.models.layer2.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:neon.transforms.cross_entropy.CrossEntropy {},
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
