# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test the FULL version of AlexNet CNN on ImageNet.
# For smaller version run i1k_gpu_small.yaml instead
# Compare to Caffe: https://github.com/BVLC/caffe/blob/master/models/bvlc_alexnet/train_val.prototxt

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:neon.backends.gpu.GPU {
    rng_seed: 0,
  },

  dataset: &ds !obj:neon.datasets.i1k.I1K {
    backend: *be,
    load_path: '/usr/local/data', #directory where .tar files are stored
    repo_path: '/usr/local/data', #directory to use for writing files
    output_image_size: &ois 256,
    cropped_image_size: &cis 224,
    max_tar_file: &mtf 1000,
    output_batch_size: 3072,
    ring_buffer_size: 3,
    num_train_macro_batches: 417, #max available train macro_batches
    num_val_macro_batches: 16, #max available val macro batches
    #number of cpu processes for image resizing and decompression
    num_processes: 4, #not impl yet
    # macro batch start and end indices to use for train and val datasets
    start_train_batch: 0,
    end_train_batch: 416,
    start_val_batch: 0,
    end_val_batch: 15,
  },

  weight_inits: &wt_init0 {
    type: normal,
    scale: .01,
    bias_init: 0.0,
  },

  weight_inits: &wt_init1 {
    type: normal,
    scale: .01,
    bias_init: 0.1,
  },

  weight_inits: &wt_init_fc {
    type: normal,
    scale: .005,
    bias_init: 0.1,
  },

  lrule: &gdm {
    type: gradient_descent_momentum,
    lr_params: {
      learning_rate: 0.02,
      backend: *be,
      schedule: {
              type: step,
              ratio: 0.1,
              step_epochs: 20,
      },
      momentum_params: {
        type: constant,
        initial_coef: 0.90,
      },
    },
  },

  lrule: &gdmwd {
    type: gradient_descent_momentum_weight_decay,
    lr_params: {
      learning_rate: 0.01,
      weight_decay: .0005,
      backend: *be,
      schedule: {
              type: step,
              ratio: 0.1,
              step_epochs: 20,
      },
      momentum_params: {
        type: constant,
        initial_coef: 0.90,
      },
    },
  },

  model: !obj:neon.models.mlp.MLPB {
    backend: *be,
    num_epochs: 90,
    batch_size: &bs 256, #128,
    serialized_path: '/usr/local/data/I1K/I1K_alexnet_model.pkl',
    layers: [
      &datalayer !obj:neon.models.layer2.DataLayer {
        name: d0,
        dataset: *ds,
        is_local: True,
        nofm: 3,
        ofmshape: [*cis, *cis],
      },
      !obj:neon.models.layer2.ConvLayer {
        name: conv1,
        lrule_init: *gdmwd,
        brule_init: *gdm,
        weight_init: *wt_init0,
        nofm: 64,
        fshape: [11, 11],
        stride: 4,
        activation: !obj:neon.transforms.rectified.RectLin {},
      },
      !obj:neon.models.layer2.CrossMapResponseNormLayer {
        name: rnorm1,
        ksize: 5,
        alpha: 0.0001,
        beta: 0.75,
      },
      !obj:neon.models.layer2.PoolingLayer {
        name: pool1,
        op: 'max',
        fshape: [3, 3],
        stride: 2,
      },
      !obj:neon.models.layer2.ConvLayer {
        name: conv2,
        lrule_init: *gdmwd,
        brule_init: *gdm,
        weight_init: *wt_init1,
        nofm: 192,
        fshape: [5, 5],
        pad: 2,
        activation: !obj:neon.transforms.rectified.RectLin {},
      },
      !obj:neon.models.layer2.CrossMapResponseNormLayer {
        name: rnorm2,
        ksize: 5,
        alpha: 0.0001,
        beta: 0.75,
      },
      !obj:neon.models.layer2.PoolingLayer {
        name: pool2,
        op: 'max',
        fshape: [3, 3],
        stride: 2,
      },
      !obj:neon.models.layer2.ConvLayer {
        name: conv3,
        lrule_init: *gdmwd,
        brule_init: *gdm,
        weight_init: *wt_init0,
        nofm: 384,
        fshape: [3, 3],
        pad: 1,
        activation: !obj:neon.transforms.rectified.RectLin {},
      },
      !obj:neon.models.layer2.ConvLayer {
        name: conv4,
        lrule_init: *gdmwd,
        brule_init: *gdm,
        weight_init: *wt_init1,
        nofm: 256,
        fshape: [3, 3],
        pad: 1,
        activation: !obj:neon.transforms.rectified.RectLin {},
      },
      !obj:neon.models.layer2.ConvLayer {
        name: conv5,
        lrule_init: *gdmwd,
        brule_init: *gdm,
        weight_init: *wt_init1,
        nofm: 256,
        fshape: [3, 3],
        pad: 1,
        activation: !obj:neon.transforms.rectified.RectLin {},
      },
      !obj:neon.models.layer2.PoolingLayer {
        name: pool3,
        op: 'max',
        fshape: [3, 3],
        stride: 2,
      },
      !obj:neon.models.layer2.FCLayer {
        name: fc4096a,
        lrule_init: *gdmwd,
        brule_init: *gdm,
        weight_init: *wt_init_fc,
        nout: 4096,
        activation: !obj:neon.transforms.rectified.RectLin {},
      },
      !obj:neon.models.layer2.DropOutLayer {
        name: dropout1,
        keep: 0.5,
      },
      !obj:neon.models.layer2.FCLayer {
        name: fc4096b,
        lrule_init: *gdmwd,
        brule_init: *gdm,
        weight_init: *wt_init_fc,
        nout: 4096,
        activation: !obj:neon.transforms.rectified.RectLin {},
      },
      !obj:neon.models.layer2.DropOutLayer {
        name: dropout2,
        keep: 0.5,
      },
      &lastlayer !obj:neon.models.layer2.FCLayer {
        name: fc1000,
        lrule_init: *gdmwd,
        brule_init: *gdm,
        weight_init: *wt_init0,
        nout: *mtf,
        activation: !obj:neon.transforms.softmax.Softmax {},
      },
      &costlayer !obj:neon.models.layer2.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:neon.transforms.cross_entropy.CrossEntropy {},
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
