# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a small CNN on ImageNet.

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:neon.backends.gpu.GPU {
    rng_seed: 0,
  },

  dataset: &ds !obj:neon.datasets.i1k.I1K {
    backend: *be,
    load_path: '/usr/local/data', #directory where .tar files are stored
    repo_path: '/usr/local/data/alex', #directory to use for writing files
    serialized_path: '/usr/local/data/alex/I1K/I1K_dataset.pkl', #delete if loading files from scratch
    # sample_pct: .1,
    max_tar_file: 4, #use this instead of sample_pct
    macro_batched: True,
    output_image_size: &ois 256,
    # macro batch start and end indices for train and val datasets
    # need #macro batches * output_batch_size to divide nrecs
    start_train_batch: 0,
    end_train_batch: 0,
    start_val_batch: 0,
    end_val_batch: 0,
  },

  weight_inits: &wt_init {
    type: uniform,
    low: -0.1,
    high: 0.1,
  },

  lrule: &gdm {
    type: gradient_descent_momentum,
    lr_params: {
      learning_rate: 0.01,
      backend: *be,
<<<<<<< HEAD
      load_path: '/usr/local/data', #directory where .tar files are stored
      repo_path: '/usr/local/data', #directory to use for writing files
      serialized_path: '/usr/local/data/I1K/I1K_dataset.pkl', #delete if loading files from scratch
      # sample_pct: .1,
      max_tar_file: 1, #4, #use this instead of sample_pct
      macro_batched: True,
      output_image_size: &ois 256,
      # macro batch start and end indices for train and val datasets
      # need #macro batches * output_batch_size to divide nrecs
      start_train_batch: 0,
      end_train_batch: 0,
      start_val_batch: 0,
      end_val_batch: 0,
=======
      momentum_params: {
        type: linear_monotone, #constant, nesterov
        initial_coef: 0.90,
        start_epoch: 5,
        saturate_epoch: 5,
        saturated_coef: 0.99,
      },
>>>>>>> master
    },
  },

  model: !obj:neon.models.mlp.MLPB {
    backend: *be,
    num_epochs: 1,
    batch_size: &bs 128,
    layers: [
      &datalayer !obj:neon.models.layer2.DataLayer {
        name: d0,
        dataset: *ds,
        nofm: 3,
        is_local: True,
        ofmshape: [*ois, *ois],
      },
      !obj:neon.models.layer2.ConvLayer {
        name: layer1,
        nofm: 16,
        fshape: [4, 4],
        stride: 4,
        lrule_init: *gdm,
        weight_init: *wt_init,
      },
      !obj:neon.models.layer2.PoolingLayer {
        name: layer2,
        op: 'max',
        fshape: [4, 4],
        stride: 4,
      },
      !obj:neon.models.layer2.ConvLayer {
        name: layer3,
        nofm: 32,
        fshape: [2, 2],
        stride: 2,
        lrule_init: *gdm,
        weight_init: *wt_init,
      },
      !obj:neon.models.layer2.PoolingLayer {
        name: layer4,
        op: 'max',
        fshape: [2, 2],
        stride: 2,
      },
      !obj:neon.models.layer2.FCLayer {
        name: layer5,
        nout: 500,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:neon.transforms.rectified.RectLin {},
      },
      &lastlayer !obj:neon.models.layer2.FCLayer {
        name: output,
        nout: 1000,
<<<<<<< HEAD
        activation: !obj:neon.transforms.softmax.Softmax {
          shortcut_deriv: True,
          },
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
=======
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:neon.transforms.logistic.Logistic {},
      },
      &costlayer !obj:neon.models.layer2.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:neon.transforms.cross_entropy.CrossEntropy {},
>>>>>>> master
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
