# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a RBM on MNIST.
# template for DBM layers

!obj:neon.experiments.fit.FitExperiment {
  backend: &be !obj:neon.backends.gpu.GPU {
    rng_seed: 0,
  },

  # MNIST data
  dataset: !obj:neon.datasets.mnist.MNIST {
    backend: *be,
    repo_path: '/usr/local/data',
    sample_pct: 100,
  },

  # RBM model specification
  model: !obj:neon.models.rbm.RBM {
    backend: *be,
    num_epochs: 60,
    batch_size: &bs 100,
    # serialized_path: './rbm-cudanet60.pkl',
    layers: [
      &rlayer !obj:neon.models.layer.RBMLayer {
        name: vis2hid,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rule: !obj:neon.models.learning_rule.GradientDescent {
          name: vis2hidlr,
          lr_params: {
            learning_rate: &lr -0.01,
            backend: *be,
          },
        },
        nin: 784,
        nout: 1000,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: normal,
          loc: 0.0,
          scale: 0.01,
        },
      },
    ],
    cost: !obj:neon.transforms.sum_squared.SumSquaredDiffs {
      olayer: *rlayer,
    },
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
