# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a 1 hidden layer Neural Net on full
# MNIST.  Parameters are optimized for performance.

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:neon.backends.cpu.CPU {
    rng_seed: 0,
    # set which numpy issues raise exceptions, warnings, etc.
    # see: numpy.seterr()
    seterr_handling: {
      all: 'warn',
    },
  },

  dataset: &ds !obj:neon.datasets.mnist.MNIST {
    backend: *be,
    repo_path: '/usr/local/data',
    sample_pct: 100,
  },

  weight_inits: [
    &wt_uni !obj:params.GaussianValGen {
      backend: *be,
      scale: 0.1,
    },
    &wt_initb !obj:params.NodeNormalizedValGen {
      backend: *be,
      scale: 4.0,
      bias_init: 0.0,
    },
  ],

  lrule: [
    &gd {
      type: gradient_descent,
      lr_params: {
        learning_rate: 0.0001,
        backend: *be,
      },
    },
  ],
  # simple MLP model specification
  model: !obj:neon.models.mlp.MLPB {
    backend: *be,
    num_epochs: 100,
    batch_size: &bs 100,
    # serialized_path: './mlp-simple.pkl',
    layers: [
      &datalayer !obj:neon.models.layer2.DataLayer {
        name: d0,
        dataset: *ds,
        nout: 784,
      },
      !obj:neon.models.layer2.FCLayer {
        name: h0,
        nout: 512,
        lrule_init: *gd,
        weight_init: *wt_uni,
        activation: !obj:neon.transforms.logistic.Logistic {},
      },
      &lastlayer !obj:neon.models.layer2.FCLayer {
        name: output,
        nout: 10,
        lrule_init: *gd,
        weight_init: *wt_uni,
        activation: !obj:neon.transforms.logistic.Logistic {},
      },
      &costlayer !obj:neon.models.layer2.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:neon.transforms.cross_entropy.CrossEntropy {},
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
