# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train a stacked autoencoder on MNIST.

!obj:neon.experiments.fit.FitExperiment {
  backend: &be !obj:neon.backends.gpu.GPU {
    rng_seed: 0,
  },

  datasets: [
    # MNIST data
    !obj:neon.datasets.mnist.MNIST {
      backend: *be,
      repo_path: '/usr/local/data',
      sample_pct: 100,
    },
  ],

  # Autoencoder model specification
  model: !obj:neon.models.autoencoder.Autoencoder {
    backend: *be,
    num_epochs: 60,
    batch_size: &bs 100,
    # serialized_path: './ae-cudanet.pkl',
    layers: [
      !obj:neon.models.layer.LayerWithNoBias {
        name: enc1,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: enc1lr,
          lr_params: {
            learning_rate: &lr 0.0001,
            backend: *be,
            momentum_params: &mm {
              type: constant, # linear_monotone, nesterov
              coef: 0.90,
            },
          },
        },
        nin: 784,  # input layer.  No bias used
        nout: 1000,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: gaussian,
          scale: 0.1,
        },
      },
      !obj:neon.models.layer.LayerWithNoBias {
        name: enc2,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: enc2lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 1000,
        nout: 500,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: gaussian,
          scale: 0.1,
        },
      },
      !obj:neon.models.layer.LayerWithNoBias {
        name: enc3,
        backend: *be,
        batch_size: *bs,
        pos: 2,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: enc3lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 500,
        nout: 250,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: gaussian,
          scale: 0.1,
        },
      },
      !obj:neon.models.layer.LayerWithNoBias {
        name: enc4,
        backend: *be,
        batch_size: *bs,
        pos: 3,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: enc4lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 250,
        nout: 30,
        weight_init: {
          type: gaussian,
          scale: 0.1,
        },
      },
      !obj:neon.models.layer.LayerWithNoBias {
        name: dec1,
        backend: *be,
        batch_size: *bs,
        pos: 4,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: dec1lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 30,
        nout: 250,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: gaussian,
          scale: 0.1,
        },
      },
      !obj:neon.models.layer.LayerWithNoBias {
        name: dec2,
        backend: *be,
        batch_size: *bs,
        pos: 5,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: dec2lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 250,
        nout: 500,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: gaussian,
          scale: 0.1,
        },
      },
      !obj:neon.models.layer.LayerWithNoBias {
        name: dec3,
        backend: *be,
        batch_size: *bs,
        pos: 6,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: dec3lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 500,
        nout: 1000,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: gaussian,
          scale: 0.1,
        },
      },
      &lastlayer !obj:neon.models.layer.LayerWithNoBias {
        name: dec4,
        backend: *be,
        batch_size: *bs,
        pos: 7,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: dec4lr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 1000,
        nout: 784,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: gaussian,
          scale: 0.1,
        },
      },
    ],
    cost: !obj:neon.transforms.cross_entropy.CrossEntropy {
      olayer: *lastlayer,
    },
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
