# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a "Google Brain" style sparse autoencoder
# model on MNIST.

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:neon.backends.cpu.CPU {
    rng_seed: 0,
  },

  datasets: [
    # MNIST data
    !obj:neon.datasets.mnist.MNIST {
      backend: *be,
      repo_path: '/usr/local/data',
      sample_pct: 10,
    },
  ],

  # Google Brain model specification
  model: !obj:neon.models.gb.GB {
    backend: *be,
    num_epochs: 4,
    num_pretrain_epochs: 2,
    num_initial_epochs: 1,
    batch_size: &bs 100,
    pretraining: &pt True,
    visualize: False,
    spot_check: False,
    layers: [
      &ilayer !obj:neon.models.layer.LocalFilteringLayer {
        name: layer0,
        pretraining: *pt,
        sparsity: &sp 0.1,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentPretrain {
          name: layer0lr,
          lr_params: {
            learning_rate: &lr 0.1,
            pretrain_learning_rate: &plr 0.01,
            backend: *be,
          },
        },
        tied_weights: &tw True,
        nifm: 1,
        nofm: 8,
        ifmshape: [28, 28],
        fshape: [4, 4],
        stride: 1,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:neon.models.layer.L2PoolingLayer {
        name: layer1,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        nifm: 8,
        ifmshape: [25, 25],
        fshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LCNLayer {
        name: layer2,
        backend: *be,
        batch_size: *bs,
        pos: 2,
        nifm: 8,
        ifmshape: [23, 23],
        fshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LocalFilteringLayer {
        name: layer3,
        pretraining: *pt,
        sparsity: *sp,
        backend: *be,
        batch_size: *bs,
        pos: 3,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentPretrain {
          name: layer3lr,
          lr_params: {
            learning_rate: *lr,
            pretrain_learning_rate: *plr,
            backend: *be,
          },
        },
        tied_weights: *tw,
        nifm: 8,
        nofm: 8,
        ifmshape: [23, 23],
        fshape: [3, 3],
        stride: 1,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:neon.models.layer.L2PoolingLayer {
        name: layer4,
        backend: *be,
        batch_size: *bs,
        pos: 4,
        nifm: 8,
        ifmshape: [21, 21],
        fshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LCNLayer {
        name: layer5,
        backend: *be,
        batch_size: *bs,
        pos: 5,
        nifm: 8,
        ifmshape: [19, 19],
        fshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LocalFilteringLayer {
        name: layer6,
        pretraining: *pt,
        sparsity: *sp,
        backend: *be,
        batch_size: *bs,
        pos: 6,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentPretrain {
          name: layer6lr,
          lr_params: {
            learning_rate: *lr,
            pretrain_learning_rate: *plr,
            backend: *be,
          },
        },
        tied_weights: *tw,
        nifm: 8,
        nofm: 8,
        ifmshape: [19, 19],
        fshape: [3, 3],
        stride: 1,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:neon.models.layer.L2PoolingLayer {
        name: layer7,
        backend: *be,
        batch_size: *bs,
        pos: 7,
        nifm: 8,
        ifmshape: [17, 17],
        fshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LCNLayer {
        name: layer8,
        backend: *be,
        batch_size: *bs,
        pos: 8,
        nifm: 8,
        ifmshape: [15, 15],
        fshape: [3, 3],
        stride: 1,
      },
      &lastlayer !obj:neon.models.layer.Layer {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 9,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: outputlr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: {
              type: constant, # linear_monotone, nesterov
              coef: 0.90,
            },
          },
        },
        nin: 1800, # previous nout (nifm * ifmshape[0] * ifmshape[1])
        nout: 10,
        activation: !obj:neon.transforms.logistic.Logistic {
          shortcut_deriv: True,
        },
        weight_dtype: &dt 'float32',
        updates_dtype: *dt,
        pre_act_dtype: *dt,
        output_dtype: *dt,
        deltas_dtype: *dt,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
    ],
    cost: !obj:neon.transforms.cross_entropy.CrossEntropy {
      olayer: *lastlayer,
    },
    pretrain_cost: !obj:neon.transforms.sum_squared.SumSquaredDiffs {
      olayer: *ilayer,
    },
  },

  # logging options that are passed to logging.basicConfig
  logging: {
    level: 20,  #logging.DEBUG == 10
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
