# Experiment settings to train/test a "Google Brain" style sparse autoencoder
# model on MNIST.

!obj:mylearn.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:mylearn.backends._numpy.Numpy {
    rng_seed: 0,
  },
  
  datasets: [
    # MNIST data
    !obj:mylearn.datasets.mnist.MNIST {
      backend: *be,
      repo_path: '/usr/local/data',
      sample_pct: 10,
      serialized_path: '/usr/local/data/MNIST/mnist_10pct-Numpy.pkl',
    },
  ],
  
  # Google Brain model specification
  model: !obj:mylearn.models.gb.GB {
    num_pretraining_epochs: 2,
    num_epochs: 2,
    batch_size: &bs 100,
    learning_rate: &lr 0.1,
    momentum: {
      type: linear_monotone,
      initial_coef: 0.99,
      start_epoch: 5,
      saturate_epoch: 5,
      saturated_coef: 0.90,
    },
    pretraining_cost: !obj:mylearn.transforms.sum_squared.SumSquaredDiffs {},
    cost: !obj:mylearn.transforms.cross_entropy.CrossEntropy {},
    layers: [
      !obj:mylearn.models.layer.LocalFilteringLayer {
        name: layer1,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rate: *lr,
        nifm: 1,
        ifmshape: [28, 28],
        fshape: [5, 5],
        stride: 1,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:mylearn.models.layer.L2PoolingLayer {
        name: layer2,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        nfm: 1,
        ifmshape: [24, 24],
        pshape: [2, 2],
        stride: 1,
      },
      !obj:mylearn.models.layer.LCNLayer {
        name: layer3,
        backend: *be,
        batch_size: *bs,
        pos: 2,
        nifm: 1,
        ifmshape: [23, 23],
        fshape: [5, 5],
        stride: 1,
      },
      !obj:mylearn.models.layer.LocalFilteringLayer {
        name: layer4,
        backend: *be,
        batch_size: *bs,
        pos: 3,
        learning_rate: *lr,
        nifm: 1,
        ifmshape: [23, 23],
        fshape: [5, 5],
        stride: 1,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:mylearn.models.layer.L2PoolingLayer {
        name: layer5,
        backend: *be,
        batch_size: *bs,
        pos: 4,
        nfm: 1,
        ifmshape: [19, 19],
        pshape: [2, 2],
        stride: 1,
      },
      !obj:mylearn.models.layer.LCNLayer {
        name: layer6,
        backend: *be,
        batch_size: *bs,
        pos: 5,
        nifm: 1,
        ifmshape: [18, 18],
        fshape: [3, 3],
        stride: 1,
      },
      !obj:mylearn.models.layer.LayerWithNoBias {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 6,
        learning_rate: *lr,
        nin: 324, # previous nout (nifm * ifmshape[0] * ifmshape[1])
        nout: 10,
        activation: !obj:mylearn.transforms.logistic.Logistic {},
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
    ],
  },
  
  # logging options that are passed to logging.basicConfig
  logging: {
    level: 10,  #logging.DEBUG == 10
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
