# Experiment settings to train/test a "Google Brain" style sparse autoencoder
# model on MNIST.

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:neon.backends._numpy.Numpy {
    rng_seed: 0,
  },

  datasets: [
    # MNIST data
    !obj:neon.datasets.mnist.MNIST {
      backend: *be,
      repo_path: '/usr/local/data',
      sample_pct: 10,
      #serialized_path: '/usr/local/data/MNIST/mnist_10pct-Numpy.pkl',
    },
  ],

  # Google Brain model specification
  model: !obj:neon.models.gb.GB {
    backend: *be,
    num_epochs: 4,
    num_pretrain_epochs: 1,
    num_initial_epochs: 1,
    batch_size: &bs 100,
    learning_rate: &lr 0.1,
    pretraining: &pt True,
    sparsity: &sp 0.1,
    pretrain_learning_rate: &plr 0.01,
    tied_weights: &tw True,
    visualize: False,
    spot_check: False,
    momentum: {
      type: linear_monotone,
      initial_coef: 0.99,
      start_epoch: 5,
      saturate_epoch: 5,
      saturated_coef: 0.90,
    },
    pretrain_cost: !obj:neon.transforms.sum_squared.sum_squareduaredDiffs {},
    cost: !obj:neon.transforms.cross_entropy.CrossEntropy {},
    layers: [
      !obj:neon.models.layer.LocalFilteringLayer {
        name: layer0,
        pretraining: *pt,
        sparsity: *sp,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rate: *lr,
        pretrain_learning_rate: *plr,
        tied_weights: *tw,
        nifm: 1,
        nofm: 8,
        ifmshape: [28, 28],
        fshape: [4, 4],
        stride: 1,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:neon.models.layer.L2PoolingLayer {
        name: layer1,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        nfm: 8,
        ifmshape: [25, 25],
        pshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LCNLayer {
        name: layer2,
        backend: *be,
        batch_size: *bs,
        pos: 2,
        nfm: 8,
        ifmshape: [23, 23],
        fshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LocalFilteringLayer {
        name: layer3,
        pretraining: *pt,
        sparsity: *sp,
        backend: *be,
        batch_size: *bs,
        pos: 3,
        learning_rate: *lr,
        pretrain_learning_rate: *plr,
        tied_weights: *tw,
        nifm: 8,
        nofm: 8,
        ifmshape: [23, 23],
        fshape: [3, 3],
        stride: 1,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:neon.models.layer.L2PoolingLayer {
        name: layer4,
        backend: *be,
        batch_size: *bs,
        pos: 4,
        nfm: 8,
        ifmshape: [21, 21],
        pshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LCNLayer {
        name: layer5,
        backend: *be,
        batch_size: *bs,
        pos: 5,
        nfm: 8,
        ifmshape: [19, 19],
        fshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LocalFilteringLayer {
        name: layer6,
        pretraining: *pt,
        sparsity: *sp,
        backend: *be,
        batch_size: *bs,
        pos: 6,
        learning_rate: *lr,
        pretrain_learning_rate: *plr,
        tied_weights: *tw,
        nifm: 8,
        nofm: 8,
        ifmshape: [19, 19],
        fshape: [3, 3],
        stride: 1,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
      !obj:neon.models.layer.L2PoolingLayer {
        name: layer7,
        backend: *be,
        batch_size: *bs,
        pos: 7,
        nfm: 8,
        ifmshape: [17, 17],
        pshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LCNLayer {
        name: layer8,
        backend: *be,
        batch_size: *bs,
        pos: 8,
        nfm: 8,
        ifmshape: [15, 15],
        fshape: [3, 3],
        stride: 1,
      },
      !obj:neon.models.layer.LayerWithNoBias {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 9,
        learning_rate: *lr,
        nin: 1800, # previous nout (nfm * ifmshape[0] * ifmshape[1])
        nout: 10,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_dtype: &dt 'float32',
        velocity_dtype: *dt,
        delta_dtype: *dt,
        updates_dtype: *dt,
        pre_act_dtype: *dt,
        output_dtype: *dt,
        berror_dtype: *dt,
        weight_init: {
          type: uniform,
          low: -0.1,
          high: 0.1,
        },
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  logging: {
    level: 10,  #logging.DEBUG == 10
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
