# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a small 1 hidden layer Neural Net on full
# MNIST, using Adadelta based updates.

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:neon.backends.gpu.GPU {
    rng_seed: 0,
    seterr_handling: { 
      all: 'warn',  # warn or raise
    },
  },
  
  datasets: [
    # MNIST data
    !obj:neon.datasets.mnist.MNIST {
      backend: *be,
      repo_path: '/usr/local/data',
      sample_pct: 100,
    },
  ],
  
  # simple MLP model specification
  model: !obj:neon.models.mlp.MLP {
    backend: *be,
    num_epochs: 10,
    batch_size: &bs 100,
    layers: [
      !obj:neon.models.layer.Layer {
        name: h0,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rule: !obj:neon.models.learning_rule.AdaDelta {
          name: h0lr,
          lr_params: {
            backend: *be,
            rho: &rh 0.95,
            epsilon: &ep 0.000001,
          },
        },
        nin: 785, # input layer + 1 for the bias
        nout: 100,
        activation: !obj:neon.transforms.rectified.RectLin {},
        weight_init: {
          type: normal,
          loc: 0.0,
          scale: 0.01,
        },
      },
      &lastlayer !obj:neon.models.layer.Layer {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        learning_rule: !obj:neon.models.learning_rule.AdaDelta {
          name: h0lr,
          lr_params: {
            backend: *be,
            rho: *rh,
            epsilon: *ep,
          },
        },
        nin: 101, # previous nout + 1 for the bias
        nout: 10,
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: {
          type: node_normalized,
          scale: 4.0,
          bias_init: 0.0,
        },
      },
    ],
    cost: !obj:neon.transforms.cross_entropy.CrossEntropy {
      olayer: *lastlayer,
    },
  },
  
  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
