# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a Balance Neural Net on full
# MNIST.

!obj:neon.experiments.fit_predict_err.FitPredictErrorExperiment {
  backend: &be !obj:neon.backends.cpu.CPU {
    rng_seed: 0,
    seterr_handling: {
      all: 'warn',
    },
  },

  datasets: [
    # MNIST data
    !obj:neon.datasets.mnist.MNIST {
      backend: *be,
      repo_path: '/usr/local/data',
      sample_pct: 100,
    },
  ],

  # simple MLP model specification
  model: !obj:neon.models.mlp.MLP {
    backend: *be,
    num_epochs: 30,
    batch_size: &bs 100,
    layers: [
      !obj:neon.models.layer.Layer {
        name: h0,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: h0lr,
          lr_params: {
            learning_rate: &lr 0.1,
            backend: *be,
            momentum_params: &mm {
              type: constant, #constant, nesterov
              initial_coef: 0.90,
            },
          },
        },
        nin: 785, # input layer + 1 for the bias
        nout: 200,
        activation: !obj:neon.transforms.rectified.RectLin {},
        weight_init: {
          type: normal,
          loc: 0.0,
          scale: 0.01,
        },
      },
      !obj:neon.models.layer.Layer {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: outputlr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 201, # previous nout + 1 for the bias
        nout: 200,
        activation: !obj:neon.transforms.rectified.Rectlin {},
        weight_init: {
          type: node_normalized,
          scale: 4.0,
          bias_init: 0.0,
        },
      },
      !obj:neon.models.layer.BranchLayer {
        sublayers: [
          !obj:neon.models.layer.Layer {
            name: output,
            backend: *be,
            batch_size: *bs,
            pos: 2,
            learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
              name: outputlr,
              lr_params: {
                learning_rate: *lr,
                backend: *be,
                momentum_params: *mm,
              },
            },
            nin: 201, # previous nout + 1 for the bias
            nout: 10,
            activation: !obj:neon.transforms.softmax.Softmax {},
            weight_init: {
              type: node_normalized,
              scale: 4.0,
              bias_init: 0.0,
            },
          },
          !obj:neon.models.layer.Layer {
            name: output,
            backend: *be,
            batch_size: *bs,
            pos: 2,
            learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
              name: outputlr,
              lr_params: {
                learning_rate: *lr,
                backend: *be,
                momentum_params: *mm,
              },
            },
            nin: 201, # previous nout + 1 for the bias
            nout: 2,
            activation: !obj:neon.transforms.softmax.Softmax {},
            weight_init: {
              type: node_normalized,
              scale: 4.0,
              bias_init: 0.0,
            },
          },
        ],
      },
      !obj:neon.models.layer.Layer {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 3,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: outputlr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 13, # previous nout + 1 for the bias
        nout: 200,
        activation: !obj:neon.transforms.rectified.Rectlin {},
        weight_init: {
          type: node_normalized,
          scale: 4.0,
          bias_init: 0.0,
        },
      },
      !obj:neon.models.layer.Layer {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 4,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: outputlr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 201, # previous nout + 1 for the bias
        nout: 200,
        activation: !obj:neon.transforms.rectified.Rectlin {},
        weight_init: {
          type: node_normalized,
          scale: 4.0,
          bias_init: 0.0,
        },
      },
      !obj:neon.models.layer.Layer {
        name: output,
        backend: *be,
        batch_size: *bs,
        pos: 5,
        learning_rule: !obj:neon.models.learning_rule.GradientDescentMomentum {
          name: outputlr,
          lr_params: {
            learning_rate: *lr,
            backend: *be,
            momentum_params: *mm,
          },
        },
        nin: 201, # previous nout + 1 for the bias
        nout: 784,
        activation: !obj:neon.transforms.linear.Linear {},
        weight_init: {
          type: node_normalized,
          scale: 4.0,
          bias_init: 0.0,
        },
      },
    ],
    cost: [
    !obj:neon.transforms.sum_squared.SumSquaredDiffs {},
    !obj:neon.transforms.cross_entropy.CrossEntropy {},
    !obj:neon.transforms.xcov.XCovariance {},
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
