# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a RBM on MNIST.
# template for DBM layers

!obj:neon.experiments.fit.FitExperiment {
  backend: &be !obj:neon.backends._cudamat.Cudamat {
    rng_seed: 0,
  },

  datasets: [
    # MNIST data
    !obj:neon.datasets.mnist.MNIST {
      backend: *be,
      repo_path: '/usr/local/data',
      sample_pct: 100,
      serialized_path: '/usr/local/data/MNIST/mnist-Cudamat.pkl',
    },
  ],

  # RBM model specification
  model: !obj:neon.models.dbn.DBN {
    backend: *be,
    num_epochs: 20,
    batch_size: &bs 100,
    learning_rate: &lr 0.01,
    momentum: {
        type: constant, # linear_monotone, nesterov
        coef: 0.90,
    cost: !obj:neon.transforms.sum_squared.SumSquaredDiffs {},
    serialized_path: './dbn-cudamat20.pkl',
    layers: [
      !obj:neon.models.layer.RBMLayer {
        name: vis2hid,
        backend: *be,
        batch_size: *bs,
        pos: 0,
        learning_rate: *lr,
        nin: 785, # num inputs + 1 for bias
        nout: 501, # num outputs + 1 for bias
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: !obj:params.GaussianValGen {
          backend: *be,
          loc: 0.0,
          scale: 0.01,
        },
      },
      !obj:neon.models.layer.RBMLayer {
        name: hid2hid,
        backend: *be,
        batch_size: *bs,
        pos: 1,
        learning_rate: *lr,
        nin: 501, # prev. outputs (incl. bias)
        nout: 1001, # num outputs + 1 for bias
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: !obj:params.GaussianValGen {
          backend: *be,
          loc: 0.0,
          scale: 0.01,
        },
      },
      !obj:neon.models.layer.RBMLayer {
        name: hid2hid2,
        backend: *be,
        batch_size: *bs,
        pos: 2,
        learning_rate: *lr,
        nin: 1001, # prev. outputs (incl. bias)
        nout: 101, # num outputs + 1 for bias
        activation: !obj:neon.transforms.logistic.Logistic {},
        weight_init: !obj:params.GaussianValGen {
          backend: *be,
          loc: 0.0,
          scale: 0.01,
        },
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
