# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ----------------------------------------------------------------------------
# MLP on CIFAR-10 with a Branch layer

!obj:experiments.FitPredictErrorExperiment {

  dataset: &ds !obj:datasets.CIFAR10 {
    repo_path: '~/data',
    sample_pct: 10, # set to 100 to sample full dataset
  },

  metrics: {
    train: [
      !obj:metrics.MisclassPercentage {},
    ],
    test: [
      !obj:metrics.MisclassPercentage {},
    ],
  },

  weight_inits: [
    &wt_init !obj:params.UniformValGen {
      low: -0.1,
      high: 0.1,
    },
  ],

  lrule: &gdm {
    type: gradient_descent_momentum,
    lr_params: {
      learning_rate: 0.01,
      momentum_params: {
        type: constant,
        coef: 0.90,
      },
    },
  },

  model: !obj:models.MLP {
    num_epochs: 100,
    batch_size: &bs 100,
    layers: [
      &datalayer !obj:layers.DataLayer {
        name: d0,
        nout: 3072,
      },
      !obj:layers.FCLayer {
        name: h0,
        nout: 200,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:transforms.RectLin {},
      },
      !obj:layers.BranchLayer {
        name: blayer,
        sublayers: [
          !obj:layers.FCLayer {
            name: blayer1,
            nout: 40,
            lrule_init: *gdm,
            weight_init: *wt_init,
            activation: !obj:transforms.RectLin {},
          },
          !obj:layers.FCLayer {
            name: blayer2,
            nout: 10,
            lrule_init: *gdm,
            weight_init: *wt_init,
            activation: !obj:transforms.RectLin {},
          },
        ],
      },
      &lastlayer !obj:layers.FCLayer {
        name: output,
        nout: 10,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:transforms.Logistic {},
      },
      &costlayer !obj:layers.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:transforms.CrossEntropy {},
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
