# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# MLP on CIFAR-10

!obj:experiments.FitPredictErrorExperiment {

  dataset: &ds !obj:datasets.CIFAR10 {
    repo_path: '~/data',
    sample_pct: 10,
  },

  weight_inits: &wt_init !obj:params.UniformValGen {
    low: -0.1,
    high: 0.1,
  },

  lrule: &gdm {
    type: gradient_descent_momentum,
    lr_params: {
      learning_rate: 0.01,
      momentum_params: {
        type: constant,
        coef: 0.90,
      },
    },
  },

  model: !obj:models.MLP {
    num_epochs: 100,
    batch_size: &bs 128,
    layers: [
      &datalayer !obj:layers.DataLayer {
        name: d0,
        nout: 3072,
      },
      !obj:layers.FCLayer {
        name: h0,
        nout: 200,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:transforms.RectLin {},
      },
      &lastlayer !obj:layers.FCLayer {
        name: output,
        nout: 10,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:transforms.Logistic {},
      },
      &costlayer !obj:layers.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:transforms.CrossEntropy {},
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
