# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# MLP on CIFAR-10
# ~10M (6M+2M) parameter network to showcase performance of pf16 kernels

!obj:experiments.FitPredictErrorExperiment {

  timing: [fprop_fp, bprop_fc, update_fc],  # a list of function this experiment should time.

  dataset: &ds !obj:datasets.CIFAR10 {
    repo_path: '~/data',
    sample_pct: 100,
  },

  weight_inits: &wt_init !obj:params.UniformValGen {
    low: -0.1,
    high: 0.1,
  },

  lrule: &gdm {
    type: gradient_descent_momentum,
    velocity_dtype: np.float16,
    lr_params: {
      learning_rate: 0.01,
      momentum_params: {
        type: constant,
        coef: 0.90,
      },
    },
  },

  model: !obj:models.MLP {
    num_epochs: 10,
    batch_size: &bs 128,
    layers: [
      &datalayer !obj:layers.DataLayer {
        name: d0,
        nout: 3072,
      },
      !obj:layers.FCLayer {
        pre_act_dtype: np.float16,
        output_dtype: np.float16,
        deltas_dtype: np.float16,
        weight_dtype: np.float16,
        updates_dtype: np.float16,
        name: h0,
        nout: 2048,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:transforms.RectLin {},
      },
      # !obj:layers.DropOutLayer {  # need fill_uniform_thresh
      #   output_dtype: np.float16,
      #   deltas_dtype: np.float16,
      #   name: dropout1,
      #   keep: 0.5,
      # },
      !obj:layers.FCLayer {
        pre_act_dtype: np.float16,
        output_dtype: np.float16,
        deltas_dtype: np.float16,
        weight_dtype: np.float16,
        updates_dtype: np.float16,
        name: h0,
        nout: 1024,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:transforms.RectLin {},
      },
      &lastlayer !obj:layers.FCLayer {
        pre_act_dtype: np.float16,
        output_dtype: np.float16,
        deltas_dtype: np.float16,
        weight_dtype: np.float16,
        updates_dtype: np.float16,
        name: output,
        nout: 10,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:transforms.Logistic {},
      },
      &costlayer !obj:layers.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:transforms.CrossEntropy {
          temp_dtype: np.float16,
          epsilon: 0.0005,
        },
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
