# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a CNN on NDSB.

!obj:experiments.FitPredictErrorExperiment {

  dataset: &ds !obj:datasets.NDSB {
      repo_path: '~/data',
      sample_pct: 100,
      image_width: 64,
      #serialized_path: '~/data/NDSB/ndsb.pkl',
  },

  weight_init: &wt_init !obj:params.UniformValGen {
    low: -0.1,
    high: 0.1,
  },

  lrules: [
      &gdm {
        type: gradient_descent_momentum,
        lr_params: {
          learning_rate: 0.01,
          momentum_params: {
            type: constant, # linear_monotone, nesterov
            coef: 0.90,
          },
        },
      },
  ],

  # CNN model specification
  # essentially a multi-layer perceptron with convolutional and pooling layers
  model: !obj:models.MLP {
    num_epochs: 20,
    batch_size: &bs 128,
    layers: [
      &datalayer !obj:layers.DataLayer {
        name: d0,
        nout: 4096,
      },
      !obj:layers.ConvLayer {
        name: layer1,
        activation: !obj:transforms.RectLin {},
        nofm: 64,
        fshape: [4, 4],
        stride: 2,
        lrule_init: *gdm,
        weight_init: *wt_init,
      },
      !obj:layers.PoolingLayer {
        name: layer2,
        op: 'max',
        fshape: [2, 2],
        stride: 2,
      },
      !obj:layers.ConvLayer {
        name: layer3,
        activation: !obj:transforms.RectLin {},
        nofm: 128,
        fshape: [3, 3],
        stride: 1,
        lrule_init: *gdm,
        weight_init: *wt_init,
      },
      !obj:layers.PoolingLayer {
        name: layer4,
        op: 'max',
        fshape: [2, 2],
        stride: 2,
      },
      !obj:layers.ConvLayer {
        name: layer3,
        activation: !obj:transforms.RectLin {},
        nofm: 256,
        fshape: [2, 2],
        stride: 1,
        lrule_init: *gdm,
        weight_init: *wt_init,
      },
      !obj:layers.PoolingLayer {
        name: layer4,
        op: 'max',
        fshape: [2, 2],
        stride: 2,
      },
      !obj:layers.FCLayer {
        name: layer5,
        nout: 1024,
        activation: !obj:transforms.RectLin {},
        lrule_init: *gdm,
        weight_init: *wt_init,
      },
      !obj:layers.DropOutLayer {
        name: dropout,
        keep: 0.5,
      },
      !obj:layers.FCLayer {
        name: layer5,
        nout: 512,
        activation: !obj:transforms.RectLin {},
        lrule_init: *gdm,
        weight_init: *wt_init,
      },
      !obj:layers.DropOutLayer {
        name: dropout,
        keep: 0.5,
      },
      &lastlayer !obj:layers.FCLayer {
        name: output,
        nout: 121,
        activation: !obj:transforms.Logistic {},
        lrule_init: *gdm,
        weight_init: *wt_init,
      },
      &costlayer !obj:layers.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:transforms.CrossEntropy {},
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
