# ----------------------------------------------------------------------------
# Copyright 2014 Nervana Systems Inc.  All rights reserved.
# ----------------------------------------------------------------------------
# Experiment settings to train/test a Balance Neural Net on full
# MNIST.

 !obj:experiments.GenOutputExperiment {
  zparam: 0.0,
  olayout: [12, 6],
  fshape: [28, 28],
  figure_filename: 'ofn.png',

  # MNIST data
  dataset: &ds !obj:datasets.MNIST {
    repo_path: '~/data',
    sample_pct: 100,
  },

  lrule: &adad {
    type: adadelta,
    lr_params: {
      epsilon: 0.000001,
      rho: 0.95,
    },
  },

  wt_cfgs: [
    &wt_init_a !obj:params.AutoUniformValGen {
      bias_init: 0.0,
    },
    &wt_init_b !obj:params.AutoUniformValGen {
      bias_init: 0.0,
      relu: 1,
    },
  ],

  # simple Balance model specification
  model: !obj:models.Balance {
    # serialized_path: './balance-simple.pkl',
    num_epochs: 20,
    batch_size: &bs 100,
    layers: [
      &datalayer !obj:layers.DataLayer {
        name: d0,
        nout: 784,
      },
      &h0 !obj:layers.FCLayer {
        name: h0,
        lrule_init: *adad,
        weight_init: *wt_init_b,
        activation: !obj:transforms.RectLin {},
        nout: 200,
      },
      &h1 !obj:layers.FCLayer {
        name: h1,
        lrule_init: *adad,
        weight_init: *wt_init_a,
        nout: 200,
      },
      &blayer !obj:layers.BranchLayer {
        name: blayer,
        sublayers: [
          &classlayer !obj:layers.FCLayer {
            name: classlayer,
            lrule_init: *adad,
            weight_init: *wt_init_a,
            activation: !obj:transforms.Softmax {},
            nout: &zidx 10,
          },
          &stylelayer !obj:layers.FCLayer {
            name: stylelayer,
            lrule_init: *adad,
            weight_init: *wt_init_a,
            nout: 2,
          },
        ],
      },
      &h3 !obj:layers.FCLayer {
        name: h3,
        lrule_init: *adad,
        weight_init: *wt_init_a,
        nout: 200,
      },
      &h4 !obj:layers.FCLayer {
        name: h4,
        lrule_init: *adad,
        weight_init: *wt_init_b,
        activation: !obj:transforms.RectLin {},
        nout: 200,
      },
      &outlayer !obj:layers.FCLayer {
        name: outlayer,
        lrule_init: *adad,
        weight_init: *wt_init_a,
        nout: 784,
      },
      &sumsqcostlayer !obj:layers.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        ref_label: output,
        cost: !obj:transforms.SumSquaredDiffs {},
      },
    ],
    classlayers: [
      *datalayer,
      *h0,
      *h1,
      *classlayer,
      &xentcostlayer !obj:layers.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:transforms.CrossEntropy {
          scale: 10,
        },
      },
    ],
    stylelayers: [
      *datalayer,
      *h0,
      *h1,
      *blayer,
      &xcovcostlayer !obj:layers.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:transforms.XCovariance {
          blkidx: 10,
          scale: 10,
        },
      },
    ],
    zidx: *zidx,
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
